name: Continuous Integration

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mypy:
    name: Type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install mypy
        run: cat dev_tools/config/pip-list-dev-tools.txt | grep mypy | xargs pip install
      - name: Type check
        run: check/mypy
  lint:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install pylint
        run: cat dev_tools/config/pip-list-dev-tools.txt | grep "pylint\|astroid" | grep -v "#" | xargs pip install
      - name: Lint
        run: check/pylint
  pytest:
    name: Pytest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install pytest
          cat dev_tools/config/pip-list-dev-tools.txt | grep pytest | grep -v "#" | xargs pip install
          git config --global user.name ${GITHUB_ACTOR}
      - name: Pytest check
        run: check/pytest --actually-quiet
